### ISSUE TITLE
Crate returns version of crate, not of my lib

### ISSUE THREAD

**Issue by matthiasbeyer** [thebreadcat/version#4]
I guess you should test this yourself.

**Comment by zummenix** [comment]
Interesting. This is because macro `std::env!` gets an environment variable at compile time. Seems like it's not possible to get correct variables without `version!`.

**Comment by matthiasbeyer** [comment]
I can get a current version with the `version!()`-Macro.

**Comment by zummenix** [comment]
When I proposed #2 I completely missed how we get crate version from cargo. Sorry for that.

**Comment by nulldatamap** [comment]
@zummenix It could be fixed by having to pass in the version string to `Version`s constructor.

**Comment by nulldatamap** [comment]
It has been dealt with in 940b1f8.
