### ISSUE TITLE
Please relicense!

### ISSUE THREAD

**Issue by matthiasbeyer** [thebreadcat/version#5]
Hi,

according to [this issue](https://github.com/matthiasbeyer/imag/issues/1212) I have to relicense my sourcecode to GPL because I use the `version` crate which is GPL.

Could you, please, relicense your code? I'd like to suggest the Mozilla Public License (MPL) 2.0 - it also gives you copyleft like the GPL, though does not force users of the library to license theirs under GPL. (LGPL is complicated because rust does static linking).

A patchlevel release after the relicense would be nice (or minor, if you think that's an imporant change) ... maybe I'll ping @steveklabnik here - New license = new minor or new patchlevel release?

**Comment by est31** [comment]
The recommended license for Rust projects is to dual license under `Apache-2.0` or `MIT`. The  Apache-2.0 license prevents the author of the software suing users for patent infringement, while the MIT is compatible with GPLv2 only software and has less weird clauses than the Apache 2.0 (apache for example requires notes about to be kept etc).

If you don't want to use the recommended dual license, MPL like @matthiasbeyer suggested is also a good option.

**Comment by steveklabnik** [comment]
> New license = new minor or new patchlevel release?

Doens't matter, as long as it's a new release. That said, I would consider arguing for a major version bump here, as that means that nobody suddenly has a license changed when upgrading.

**Comment by juleskers** [comment]
As an outsider (coming from [here](https://users.rust-lang.org/t/relicensing-software/15045?u=juleskers)), I do not wish to push one way or the other; if you relicense _at all_ is your decision as author :-) !

However, _if_ you decide to relicense, YES to major version bump!
I say this as someone who is currently wading through 300+ libraries under sundry licenses for a Java project's dependencies (with lawyer assistance even).

A license change affects with which external code your library can be used, even though it is technically identical. This is just as much an API change as changing a functions' contract; so, in my humble opinion, most definitely a breaking change!

As you have discovered, license intercompatibility is a big enough hassle that you don't want to force a change (and thus re-evaluation) onto unsuspecting users doing "trivial" patch or minor upgrades.

**Comment by nulldatamap** [comment]
Sorry for the late response.
I've changed the license to MIT/Apache-2.0, and bumped the version number to 3.0.0.

**Comment by juleskers** [comment]
Thanks for the version bump! :-)
